name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Create ZIP
        run: |
          zip -r release.zip api _locales manifest.json background.js LICENSE CONTRIBUTORS.md README.md

      - name: Rename ZIP to .xpi
        run: |
          mv release.zip release.xpi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.ref }}
          files: release.xpi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

